[unix_http_server]
file = /dev/shm/supervisor.sock        ; (the path to the socket file)

[supervisord]
logfile = /var/log/supervisor/main.log ; (main log file;default $CWD/supervisord.log)
stdout_logfile_maxbytes = 0            ; (max main logfile bytes b4 rotation;default 50MB;must be zero if output is /dev/stdout)
loglevel = info                        ; (log level;default info; others: debug,warn,trace)
pidfile = /tmp/supervisord.pid         ; (supervisord pidfile;default supervisord.pid)
nodaemon = false                       ; (start in foreground if true;default false)
minfds = 1024                          ; (min. avail startup file descriptors;default 1024)
minprocs = 200                         ; (min. avail process descriptors;default 200)
user = root                            ;
; get env variable set in kubernetes deployment.yaml.
; It will be used in set-env program to run appropriate script.
environment=AXS_ENV="%(ENV_env)s"

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///dev/shm/supervisor.sock ; use a unix:// URL  for a unix socket

[include]
files = /etc/supervisor/conf.d/*.conf

; this program must be run first and only once.
; It will run appropriate script based on
; env variable set in kubernetes deployment.yaml
; and after that will start php-fpm8.1 and nginx
[program:set-env]
command=/sbin/set-env.sh
autostart=true
autorestart=false
startretries=0
redirect_stderr=true
stdout_logfile_maxbytes = 0
stdout_logfile=/var/log/supervisor/set-env.log

[program:axs-env-log]
command=tail -n+0 -f /var/log/axs_env.log
autostart=false
autorestart=unexpected
redirect_stderr=true
stdout_logfile_maxbytes = 0
stdout_logfile=/proc/1/fd/1

[program:graylog-sidecar]
command=/usr/bin/graylog-sidecar
autostart=false
autorestart=unexpected
redirect_stderr=true
stdout_logfile_maxbytes = 0
stdout_logfile=/var/log/supervisor/graylog-sidecar.log

[program:axsmarine-general-log]
command=tail -n+0 -f /var/log/axsmarine-general.log
autostart=false
autorestart=unexpected
redirect_stderr=true
stdout_logfile_maxbytes = 0
stdout_logfile=/proc/1/fd/1

[program:axsmarine-audit-log]
command=tail -n+0 -f /var/log/axsmarine-audit.log
autostart=false
autorestart=unexpected
redirect_stderr=true
stdout_logfile_maxbytes = 0
stdout_logfile=/proc/1/fd/1

[program:supervisord-main-log]
command=tail -n+0 -f /var/log/supervisor/main.log
autostart=false
autorestart=unexpected
redirect_stderr=true
stdout_logfile_maxbytes = 0
stdout_logfile=/proc/1/fd/1

[program:start-python]
command=/sbin/start-python.sh
autostart=false
autorestart=false
redirect_stderr=true
stdout_logfile_maxbytes = 0
stdout_logfile=/var/log/axsmarine-general.log
